### ISSUE TITLE
what is the get parameters call back ?

### ISSUE THREAD

**Issue by webineh** [codeigniters/BankMellat#3]
i used the send method work fine but in callback , What parameters are necessary ؟؟

please Explain the $params in get function , you use just  _POST

**Comment by codeigniters** [comment]
Bank will send all needed parameters through POST, so you could just send $_POST to the librarie's get function.
Now we'll have tow possible response from get function. The answer could be FALSE on settle or verifing failure or an array containing on success.
Indexes of returned array are:
ResCode: 0 = Success Payment
RefId
SaleOrderId
SaleReferenceId

**Comment by codeigniters** [comment]
Bank will send all needed parameters through POST, so you could just send $_POST to the librarie's get function.
Now we'll have tow possible response from get function. The answer could be FALSE on settle or verifing failure or an array on success.
Indexes of returned array are:
ResCode: 0 = Success Payment
RefId
SaleOrderId
SaleReferenceId

**Comment by mavinoo** [comment]
Bank will send all needed parameters through `POST`, so you could just send `$_POST` to the librarie's get function.
Now we'll have tow possible response from get function. The answer could be `FALSE` on settle or verifing failure or an array on success.
Indexes of returned array are:
ResCode: 0 = Success Payment
RefId
SaleOrderId
SaleReferenceId
